TEII-2300: prevent immidiate clear selection
inspera/hypothesis-client pull request #209
Opened 2022-04-15 12:29 UTC by sergeyvdovareize

2022-04-15 13:50 UTC, B612nian reviewed
Do we need to reset `this._focusedTime` back to `null` at some point?

2022-04-15 13:52 UTC, sergeyvdovareize commented
It's not needed. Just need to prevent that immidiate cases

2022-04-15 14:08 UTC, B612nian requested changes

2022-04-15 14:08 UTC, B612nian commented on src/annotator/guest.coffee
> +      return false;
Please add a comment explaining why the 100 millis threshold was needed and also mention the ticket for future reference.

2022-04-15 16:06 UTC, B612nian requested changes

2022-04-15 16:06 UTC, B612nian commented on src/annotator/guest.coffee
> +    # Because of several rerenders and click events in some cases the tooltip appears and immidiately dissappears
immediately

2022-04-15 16:06 UTC, B612nian commented on src/annotator/guest.coffee
> +    # Otherwise it's made not mannually by a human
manually

2022-04-18 14:01 UTC, B612nian commented
Hallo, @HuiguangChu. I see you were involved in some annotation bugfixing in the past related to Grading. I wonder if you see any deal-breakers with the approach taken in this PR that would be incompatible with the Grading side.

2022-04-18 14:02 UTC, B612nian reviewed
Asking @HuiguangChu for help on the review.

2022-04-22 14:07 UTC, B612nian commented
I have asked Swati to coordinate with the other team so that @HuiguangChu can spend 45min code-reviewing this PR in the next 3 weeks.

2022-05-06 11:58 UTC, B612nian approved these changes
Approving and booking a testing slot for it next week: https://inspera.atlassian.net/wiki/spaces/TESTC/pages/3813113857/MVP10+Testing+Plan+09+05+22-13+05+22

**Do not merge** until it reaches its testing turn.

2022-05-20 10:53 UTC, merged