IA1-4183_focus-question-and-scroll
inspera/hypothesis-client pull request #79
Opened 2020-10-28 02:49 UTC by andreyshepilov

2020-10-28 13:23 UTC, jarlep commented on src/annotator/guest.coffee
> +      if isEqual(incomingSelector, anchor.target.selector)
Not sure how underscore is adding in size to the bundle, but could not simply be written as:
`JSON.stringify(incomingSelector) === JSON.stringify(anchor.target.selector)`? That way we avoid adding a utility library for just doing one thing.

2020-10-30 09:49 UTC, jarlep reviewed
Can't see anything bad here. I think this needs a review from @sergeyvdovareize

2020-10-30 13:14 UTC, sergeyvdovareize requested changes

2020-10-30 13:14 UTC, sergeyvdovareize commented on src/annotator/guest.coffee
> +    this.config.onAnnotationClick(selector)
Technically any parameter is optional. So it's better to check it first

2020-10-30 21:42 UTC, andreyshepilov commented on src/annotator/guest.coffee
> +    [].forEach.call annotationNodesList, (el) ->
Not sure that this will work for nodes collection

2020-10-31 13:23 UTC, andreyshepilov commented on src/annotator/guest.coffee
> +        @scrollToAnnotation(anchor)
Unfortunately we can't, because we are using it in standard scroll handler as well with selector argument

2020-11-02 14:44 UTC, sergeyvdovareize commented on src/annotator/guest.coffee
> +    selector
do you need this?

2020-11-02 15:23 UTC, sergeyvdovareize approved these changes

2020-11-03 08:08 UTC, merged